Resources:
  SeaNewsArticlesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sea-news-articles

  WarcInputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sea-warc-input

  BatchTaskECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: sea-batch-task-repo

Outputs:
  SeaNewsArticlesBucket:
    Description: "The name of the bucket for storing news articles"
    Value: !Ref SeaNewsArticlesBucket
    Export:
      Name: SeaNewsArticlesBucket
  WarcInputBucket:
    Description: "The name of the bucket for WARC input files"
    Value: !Ref WarcInputBucket
    Export:
      Name: WarcInputBucket
  BatchTaskECRRepository:
    Description: "The ECR repository for the batch processing task"
    Value: !Ref BatchTaskECRRepository
    Export:
      Name: BatchTaskECRRepository
  BatchTaskECRRepositoryURI:
    Description: "The URI of the ECR repository"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BatchTaskECRRepository}:latest"
    Export:
      Name: BatchTaskECRRepositoryURI
