Resources:
  SeaNewsArticlesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sea-news-articles

  WarcInputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sea-warc-input

  BatchTaskECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: sea-batch-task-repo
