AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for Sea S3 Resources

Parameters:
  SeaNewsArticlesBucketName:
    Type: String
    Default: sea-news-articles
    Description: "Name of the S3 bucket for storing news articles"
  WarcInputBucketName:
    Type: String
    Default: sea-warc-input
    Description: "Name of the S3 bucket for WARC input files"

Resources:
  SeaNewsArticlesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref SeaNewsArticlesBucketName

  WarcInputBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref WarcInputBucketName

Outputs:
  SeaNewsArticlesBucket:
    Description: "The name of the bucket for storing news articles"
    Value: !Ref SeaNewsArticlesBucket
  WarcInputBucket:
    Description: "The name of the bucket for WARC input files"
    Value: !Ref WarcInputBucket
